[package]
name = "rusty-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.135"
serde_test = "1.0.177"
tokio = { version = "1.43.0", features = ["full"] }
uuid = "1.12.0"
