GET http://127.0.0.1:3000/pricelist/01-01-2025

###

GET http://127.0.0.1:3000/power-consumer

###

POST http://127.0.0.1:3000/power-consumer/switch.audi_charger_breaker_switch/consumption-plan?consumptionDuration=-12&finishAt=1737500232225

###

DELETE http://127.0.0.1:3000/power-consumer/switch.audi_charger_breaker_switch/consumption-plan
