// to run following requests you need to install vscode extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@tuya_switch_name = switch.audi_charger_breaker_switch
@server_address = http://127.0.0.1:3000

###
//Returns today price list
GET {{server_address}}/pricelist/{{$localDatetime 'DD-MM-YYYY'}}

###


###
// Returns list of configured power consumers, power consumer represents single Tuya switch
GET {{server_address}}/power-consumer/

###
// Create consumption plan for selected switch, 
//charing for 60 minutes, which should end three hours from now

POST {{server_address}}/power-consumer/{{tuya_switch_name}}/consumption-plan
    ?consumptionDuration=3600000
    &finishAt={{$timestamp 3 h}}000

###
// Create consumption plan for selected switch, 
//charing for 60 minutes which should end three minutes from now

POST {{server_address}}/power-consumer/{{tuya_switch_name}}/consumption-plan
    ?consumptionDuration=60000
    &finishAt={{$timestamp 3 m}}000

###
//Cancel current consumption plan
DELETE {{server_address}}/power-consumer/{{tuya_switch_name}}/consumption-plan
